[Backpropagation reference](https://cs229.stanford.edu/notes-spring2019/backprop.pdf)

In [8]:
import numpy as np

In [40]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))
def sigmoid_p(z):
    return sigmoid(z)*(1-sigmoid(z))

In [54]:
x1 = 0.5*np.ones((2,1))
w1 = np.ones((3,2))
b1 = -0.5*np.ones((3,1))
z2 = w1@x1 + b1
a2 = sigmoid(z2)
"-----"
w2 = np.ones((2,3))
b2 = -0.5*np.ones((2,1))
z3 = w2@a2 + b2
a3 = sigmoid(z3)
"-----"
w3 = np.ones((1,2))
b3 = -0.5*np.ones((1,1))
z4 = w3@a3 + b3
a4 = sigmoid(z4)

print(f"z2:{z2} a2:{a2} \nz3:{z3} a3:{a3} \nz4:{z4} a4:{a4}")

z2:[[0.5]
 [0.5]
 [0.5]] a2:[[0.62245933]
 [0.62245933]
 [0.62245933]] 
z3:[[1.36737799]
 [1.36737799]] a3:[[0.7969562]
 [0.7969562]] 
z4:[[1.0939124]] a4:[[0.74911774]]


In [55]:
y = 0

In [110]:
d4 = (a4-y)@sigmoid_p(z4)
d4

array([[0.14078945]])

In [116]:
dw3 = d4 @ a3.T
dw3

array([[0.11220303, 0.11220303]])

In [118]:
db3 = d4 
db3

array([[0.14078945]])

In [121]:
d3 = w3.T @ d4 * sigmoid_p(z3)
d3

array([[0.02278213],
       [0.02278213]])

In [122]:
dw2 = d3 @ a2.T
dw2

array([[0.01418095, 0.01418095, 0.01418095],
       [0.01418095, 0.01418095, 0.01418095]])

In [124]:
db2 = d3
db2

array([[0.02278213],
       [0.02278213]])

In [125]:
d2 = w2.T @ d3 * sigmoid_p(z2)
d2

array([[0.01070777],
       [0.01070777],
       [0.01070777]])

In [127]:
dw1 = d2 @ x1.T
dw1

array([[0.00535388, 0.00535388],
       [0.00535388, 0.00535388],
       [0.00535388, 0.00535388]])

In [128]:
db1 = d2